# Generated by Django 4.1.3 on 2022-11-30 14:00

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0002_learner_enrollment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="date_enrolled",
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
