# Generated by Django 4.1.3 on 2022-12-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("CRUD", "0006_delete_test_remove_course_learners"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="learners",
            field=models.ManyToManyField(through="CRUD.Enrollment", to="CRUD.learner"),
        ),
    ]
